List<String> tasksIveDoneHupu = [
  'Flutter Development: Developed and maintained a hospital management system in Flutter, implementing state management using Riverpod for improved performance and modularity.',
  'Firestore Transactions & Performance Optimization: Engineered efficient Firestore transactions to manage 5,000+ patient records, ensuring data consistency and atomic updates.',
  'Security & Data Integrity: Improved security by refining the encryption/decryption process, reducing data loss from 25% to 0% through custom encryption methods.',
  'Cloud Functions & Backend Automation: Designed and deployed Google Cloud Functions (Node.js) to automate scheduled tasks, reducing manual intervention by 60%.',
  'UI/UX Enhancements: Created custom UI components with adaptive layouts, improving user engagement and reducing bounce rates by 30%',
  'State Management & Performance Tuning: Integrated caching strategies and lazy loading techniques, reducing backend read costs by 45% and improving app performance.',
  'Vue.js & Frontend Dashboard Development: Developed hospital system dashboards using Vue.js, incorporating dynamic UI elements, data visualization, and real-time updates from the backend.',
  'Internationalization (i18n) & Multi-Language Support: Implemented internationalization for multilingual support, enabling seamless adaptation to different user locales.',
  'Pagination & Data Handling: Designed custom pagination for large datasets, improving response times by 35%.',
  'GoRouter Navigation & Deep Linking: Structured GoRouter-based navigation to manage deep linking scenarios efficiently in Flutter applications.',
  'Test-Driven Development & Quality Assurance: Applied TDD methodologies, writing unit tests and integration tests, leading to a 55% improvement in code reliability.',
  'Designed and implemented a user authentication and authorization system using ASP.NET Core Identity, securing over 5,000+ users.',
  'Integrated email-based password reset functionality, improving user retention and security.',
  'Developed RESTful APIs for a hospital management system, reducing server response time by 40% through optimized database queries and caching.',
  'Implemented role-based access control (RBAC), ensuring data security compliance.',
  'Optimized Entity Framework Core queries, leading to 30% faster data retrieval in high-traffic scenarios.',
  'Scrum & Agile Collaboration: Actively participated in Scrum sprints, conducted code reviews, and contributed to internal documentation efforts.',
  'Mentorship & Knowledge Sharing: Led internal workshops and training sessions, boosting team productivity by 25% and reducing project completion time by 15%.',
];
